name: CI reUse Build
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  nodeJS_Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: npm install
        name: download nodeJS dependencies
        if: inputs.appType == 'nodeJS'
      - run: mvn package
        name: download Maven dependencies 
        if: inputs.appType == 'maven'