name: CI reUse Build
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
      docker_build:
        required: true
        type: string
    secrets:
      vault_token:
        required: false
jobs:
  Build:
    runs-on: self-hosted
    env:
      vault_token: ${{ secrets.VAULT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: download nodeJS dependencies
        if: inputs.appType == 'nodeJS'
        run: npm install
      - name: download Maven dependencies 
        if: inputs.appType == 'maven'
        run: mvn package
      - name: download go dependencies 
        if: inputs.appType == 'go'  
        run: go version      
      - name: Import Secrets Azure 
        if: inputs.docker_build == 'true' && secrets.vault_token != ''
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://vault-int.harshaldevops.online:8200
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
      - name: docker build
        if: inputs.docker_build == 'true'
        run: |
          az login --service-principal --username "${ARM_CLIENT_ID}" --password "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          az acr login --name harshalhp
          docker build -t harshalhp.azurecr.io/${{ inputs.appName }}:${{ github.sha }} .
          docker push harshalhp.azurecr.io/${{ inputs.appName }}:${{ github.sha }}