name: CICD ReUse - Main
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  Build:
    uses: Harshal-HP/roboshop-github-actions/.github/workflows/Build.yml@main
    with:
      appType: '${{ inputs.appType }}'
  Test:
    runs-on: self-hosted
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo npm install
          echo npm test
        name: Run nodeJS tests
        if: inputs.appType == 'nodeJS'
      - run: echo mvn test
        name: Run Maven tests
        if: inputs.appType == 'maven'
  Deploy:
    runs-on: self-hosted
    needs: Test
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  Dev_apply:
    runs-on: self-hosted
    environment: DEV
    needs: Deploy
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  QA_apply:
    runs-on: self-hosted
    environment: QA
    needs: Dev_apply
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  UAT_apply:
    runs-on: self-hosted
    environment: UAT
    needs: QA_apply
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  Prod_apply:
    runs-on: self-hosted
    environment: PROD
    needs: UAT_apply
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."