name: CI - PR
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  Build:
    uses: Harshal-HP/roboshop-github-actions/.github/workflows/Build.yml@main
    with:
      appType: '${{ inputs.appType }}'
  Test:
    runs-on: self-hosted
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo npm install
          echo npm test
        name: Run nodeJS tests
        if: inputs.appType == 'nodeJS'
      - run: echo mvn test
        name: Run Maven tests
        if: inputs.appType == 'maven'