name: CI - PR
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName: 
        required: true
        type: string
jobs:
  Build:
    uses: Harshal-HP/roboshop-github-actions/.github/workflows/Build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
  Test:
    uses: Harshal-HP/roboshop-github-actions/.github/workflows/Test.yml@main
    needs: Build
    with:
      appType: '${{ inputs.appType }}'