name: Helm Deploy
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      vault_token:
        required: false
jobs:
  DEPLOY:
    runs-on: self-hosted
    environment: DEV
    env:
      vault_token: ${{ secrets.VAULT_TOKEN }}
    steps:
      - name: Import Secrets Azure 
        if: inputs.docker_build == 'true' && env.vault_token != ''
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: http://vault-int.harshaldevops.online:8200
          token: ${{ secrets.vault_token }}
          secrets: |
            roboshop-infra/data/azure-sp ARM_CLIENT_ID | ARM_CLIENT_ID ;
            roboshop-infra/data/azure-sp ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            roboshop-infra/data/azure-sp ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID ;
            roboshop-infra/data/azure-sp ARM_TENANT_ID | ARM_TENANT_ID ;
      - name: Deploy
        run: |
          az login --service-principal --username "${ARM_CLIENT_ID}" --password "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          az acr login --name harshalhp
          docker build -t harshalhp.azurecr.io/${{ inputs.appName }}:${{ github.sha }} .
          docker push harshalhp.azurecr.io/${{ inputs.appName }}:${{ github.sha }}